import { Button, Input, Text, View } from '@tarojs/components';
import Taro, { useRouter } from '@tarojs/taro';
import { useEffect, useState } from 'react';
import { ApiError } from '../../services/api';
import { getChatMessages, sendChatMessage, type ChatMessage } from '../../services/content';
import './index.scss';

const CustomerPage = () => { const { params } = useRouter(); const toUid = Number(params["to_uid"]) || 0; const [rows, setRows] = useState<readonly ChatMessage[]>([]); const [text, setText] = useState(''); const [connected, setConnected] = useState(false); const [loading, setLoading] = useState(true); const load = () => { setLoading(true); void getChatMessages({ toUid }).then((items) => { setRows(items); setConnected(true); }).catch((error: unknown) => { setConnected(false); void Taro.showToast({ title: error instanceof ApiError ? error.message : '客服连接失败，可稍后重试', icon: 'none' }); }).finally(() => setLoading(false)); }; useEffect(load, []); const send = async (): Promise<void> => { if (!text.trim()) return; try { await sendChatMessage(text, toUid); setText(''); } catch (error: unknown) { void Taro.showToast({ title: error instanceof ApiError ? error.message : '消息发送失败', icon: 'none' }); } }; return <View className='page customer'><View className='status'>{connected ? '客服记录已连接' : '客服暂不可用'}{!connected && <Button size='mini' onClick={load}>重试</Button>}</View><View className='chat'>{loading && <Text>正在连接客服…</Text>}{!loading && !connected && <Text>客服记录暂不可用，请稍后重试</Text>}{rows.map((row) => <View className={`bubble ${row.mine ? 'mine' : ''}`} key={row.id}>{row.type === 'image' && row.image ? <ImageFallback src={row.image} /> : <Text>{row.text}</Text>}</View>)}</View><View className='composer'><Input value={text} onInput={(event) => setText(event.detail.value)} onConfirm={() => void send()} placeholder='当前版本暂不支持发送' confirmType='send' disabled={!connected} /><Button size='mini' onClick={() => void send()} disabled={!connected}>发送</Button></View></View>; };
const ImageFallback = ({ src }: Readonly<{ src: string }>) => <Text className='imageFallback'>[图片] {src}</Text>;
export default CustomerPage;
